In [1]:
bin(25) # converst in bynary

'0b11001'

In [4]:
int(0b11001) # binary to number

25

In [5]:
oct(25)

'0o31'

In [8]:
hex(25)

'0x19'

In [1]:
bin(50)

'0b110010'

In [2]:
int(0b110010)

50

In [9]:
oct(25)

'0o31'

In [10]:
int(0o31)

25

In [12]:
1**0

1

In [16]:
(8*1**0) + (8*3**1)

32

In [17]:
8**0

1

In [18]:
oct(30)

'0o36'

In [19]:
int(0o36)

30

In [20]:
hex(25)

'0x19'

In [21]:
int(0x19)

25

In [22]:
a,b = 10,20
a,b=b,a
print(a,b)

20 10


In [23]:
a,b = 10,20
t=a
a=b
b=t
print(a,b)

20 10


In [30]:
a1=10
b1=20
a3=a1+b1
a1=a3-b1
b1=a3-a1
print(a1,b1)

10 20


In [31]:
s={1,1,2,2,3,3,4,4}

In [32]:
s

{1, 2, 3, 4}

In [33]:
a,b = 10,20
a=a+b
b=a-b
a=a-b
print(a,b)

20 10


In [34]:
a,b = 10,20
a=a*b
b=a//b
a=a//b
print(a,b)

20 10


In [35]:
a,b = 10,20
a=a^b
b=a^b
a=a^b
print(a,b)

20 10


In [36]:
a,b = 10,20
a=a^b

In [37]:
a

30

In [38]:
b=a^b

In [39]:
b

10

In [40]:
a=a^b
a

20

# 24/01/26

In [1]:
import math
math.sqrt(25)

5.0

In [2]:
x1=math.sqrt(15)
x1

3.872983346207417

In [5]:
print(math.floor(3.87)) # floor is lower value

3


In [6]:
print(math.ceil(3.87)) # ceil is upper valueprint

4


In [7]:
round(3.34)

3

In [8]:
print(math.pow(3,2)) # calculate the power 

9.0


In [9]:
math.pi

3.141592653589793

In [10]:
math.e # is e is  apsolon value

2.718281828459045

In [11]:
import math as m
m.pow(3,2)

9.0

In [12]:
from math import sqrt,pow # math has many function if you want to import specific 
print(pow(2,3))
print(m.sqrt(10))
print(m.floor(3.5))
print(m.ceil(3.6))

8.0
3.1622776601683795
3
4


In [13]:
from math import *
print(pow(2,3))
print(m.sqrt(10))
print(m.floor(3.5))
print(m.ceil(3.6))

8.0
3.1622776601683795
3
4


# input() function in python

In [14]:
x= input()
x

 2


'2'

In [15]:
type(x)

str

In [16]:
x= input()
y=input()
z= x+y
print(z)

 2
 3


23


In [17]:
x= int(input())
y=int(input())
z= x+y
print(z)

 2
 5


7


In [18]:
x= int(input("enter a first number : "))
y=int(input("enter a second number :"))
z= x+y
print(z)

enter a first number :  65
enter a second number : 654


719


In [19]:
x= (input("enter a first number : "))
y=(input("enter a second number :"))
z= x+y
print(z)

enter a first number :  25
enter a second number : 56


2556


In [22]:
st = input('enter a string')
print(st)


enter a string hello


hello


In [23]:
print(st[0])

h


In [24]:
print(st[0:3])

hel


In [25]:
st = input('enter a string')[1]
print(st)

enter a string ,jg


j


In [26]:
st = input('enter a string')[5:8]
print(st)

enter a string nareshit


hit


In [27]:
st = input('enter a string')
print(st)

enter a string 2+3-1*4


2+3-1*4


In [28]:
st = eval(input('enter a string'))

print(st)

enter a string 2+3-1*4


1


In [6]:
t =('nilesh',22,2+3j,2654.68)
t

('nilesh', 22, (2+3j), 2654.68)

In [7]:
len(t)

4

In [8]:
type(t)

tuple

In [9]:
t[0]

'nilesh'

In [12]:
t.count('nilesh')

1

In [13]:
t.index(22)

1

In [14]:
t=('nilesh','ram','kumar','suraj')
t

('nilesh', 'ram', 'kumar', 'suraj')

In [15]:
len(t)

4

In [16]:
for i in t:
    print(i)

nilesh
ram
kumar
suraj


In [17]:
for i in enumerate(t):
    print(i)

(0, 'nilesh')
(1, 'ram')
(2, 'kumar')
(3, 'suraj')


In [1]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [1]:
import numpy as np

In [3]:
a=np.arange(0,50).reshape(5,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [5]:
np.size(a)

50

In [7]:
a[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [10]:
a[-1]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
a[::-1]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [14]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [16]:
a.itemsize

8

In [18]:
print(type(a))

<class 'numpy.ndarray'>


In [19]:
len(a)

5

In [20]:
import matplotlib.pyplot as plt


In [24]:
a=[1,2,3,4,5,9,7,8,92,4,5,9,6]
b=[58,48,2,5,7,9,2,4,6,9,3,4]

plt.show()